# Generated by Django 4.2.30 on 2026-05-23 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0002_constraints'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_tier_094047_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_country_5b383b_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_joined__21ddfb_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_custome_6c3a7f_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_order_d_6e39a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_status_762191_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_categor_4083ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_price_fe467e_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_created_90bc4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_product_3516b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_custome_a5b696_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_rating_17e8a4_idx',
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecom_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecom_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecom_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecom_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user', 'tier'], name='customers_user_id_6e26ca_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user', 'country'], name='customers_user_id_0b9a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user', 'joined_date'], name='customers_user_id_96fec1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'customer'], name='orders_user_id_79a6f5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'order_date'], name='orders_user_id_49d1fd_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_user_id_17dbdf_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'category'], name='products_user_id_06d7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'price'], name='products_user_id_5cf1eb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'created_date'], name='products_user_id_886012_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'product'], name='reviews_user_id_f3980e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'customer'], name='reviews_user_id_61dc9f_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'rating'], name='reviews_user_id_066621_idx'),
        ),
    ]
