# Generated by Django 4.2.30 on 2026-05-21 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conversation_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('generated_sql', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('result_preview', models.JSONField(blank=True, default=dict)),
                ('chart_type', models.CharField(blank=True, max_length=20)),
                ('chart_config', models.JSONField(blank=True, default=dict)),
                ('safety_report', models.JSONField(blank=True, default=dict)),
                ('result_rows', models.IntegerField(default=0)),
                ('execution_ms', models.IntegerField(default=0)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('conversation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'query_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_favorite'], name='query_histo_is_favo_8f3770_idx'), models.Index(fields=['created_at'], name='query_histo_created_3c47e7_idx')],
            },
        ),
    ]
