import logging
from sql_assistant.services.schema_inspector import SchemaInspector

logger = logging.getLogger('sql_assistant')


class SuggestionGenerator:

    def generate(self):
        """
        Dynamically analyzes the database schema and generates a list of
        high-value natural language query suggestions for the user.
        """
        try:
            inspector = SchemaInspector()
            schema = inspector.get_schema()
            tables = schema.get('tables', {})

            suggestions = []

            # 1. Base suggestions if e-commerce tables are present
            if 'customers' in tables:
                suggestions.append("Which country has the highest number of my customers?")
                suggestions.append("What is the total number of my customers in each tier?")

            if 'products' in tables:
                suggestions.append("Show my top 5 most expensive products in stock")
                suggestions.append("List my top 5 brands by average product price")
                suggestions.append("List my products that are low on stock (less than 15 units)")

            if 'orders' in tables and 'customers' in tables:
                suggestions.append("What is my total revenue generated by each customer tier?")
                suggestions.append("Who are my top 5 customers by total spending?")

            if 'orders' in tables:
                suggestions.append("What is my monthly trend of order volume and revenue?")
                suggestions.append("Show the count of my orders by their current status")
                suggestions.append("What is my total spending?")

            if 'order_items' in tables and 'products' in tables:
                suggestions.append("Show my top 10 products by total revenue generated")
                suggestions.append("Which category do I buy most?")

            if 'reviews' in tables and 'products' in tables:
                suggestions.append("What are my top 5 brands by average customer rating?")
                suggestions.append("Show my products with more than 3 reviews and an average rating above 4.0")

            # Fallback/default list if tables don't match e-commerce schema exactly
            if not suggestions:
                suggestions = [
                    "Show all tables in the database",
                    "List the first 10 rows of the largest table",
                    "Show summary statistics for all numeric columns",
                ]

            logger.info("Generated %d query suggestions based on database schema", len(suggestions))
            return suggestions

        except Exception as e:
            logger.error("Error generating query suggestions: %s", str(e))
            return [
                "What is my total revenue?",
                "Show my top 10 products by revenue",
                "Which of my customers spent the most money?",
                "What is the monthly trend of my orders?",
            ]
